name: Build Native, Publish Release & Pages


on:
  push:
    branches: # Automatically trigger when pushing to main branch
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub UI


# Set required permissions
permissions:
  contents: write  # Allow creating release
  pages: write     # Allow deploying GitHub Pages
  id-token: write  # For GitHub Pages deployment

jobs:
  build-and-release: # Job 1: Build native executable
    # Matrix strategy: build Intel, ARM, and Linux versions simultaneously
    strategy:
      matrix:
        arch: [intel, arm, linux]  # 添加 linux 架構
        include:
          # Intel settings
          - arch: intel
            runner: macos-13  # Use macOS 13 (Intel) runner
            target_platform: darwin-x86_64  # GraalVM target platform
            artifact_name: generator-cli-darwin-x86_64  # Artifact name matches target_platform
            memory_options: ""
            build_options: ""
          # ARM settings
          - arch: arm
            runner: macos-latest  # Use macOS-latest (ARM, only 7GB RAM)
            target_platform: darwin-aarch64  # GraalVM target platform
            artifact_name: generator-cli-darwin-aarch64  # Artifact name matches target_platform
            memory_options: ""
            build_options: ""
          # Linux settings
          - arch: linux
            runner: ubuntu-latest  # Use Ubuntu latest runner
            target_platform: linux-x86_64  # GraalVM target platform
            artifact_name: generator-cli-linux-x86_64  # Artifact name matches target_platform
            memory_options: ""
            build_options: ""

    # Select runner based on matrix variable
    runs-on: ${{ matrix.runner }}

    steps:
      # Checkout repository (shallow checkout for speed)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Setup GraalVM environment
      - name: Setup GraalVM with Java 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          
      # Setup Gradle cache
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Cache GraalVM Native Image build results
      - name: Cache GraalVM Native Image
        uses: actions/cache@v3
        with:
          path: build/native
          key: ${{ runner.os }}-graalvm-native-${{ github.sha }}
          restore-keys: ${{ runner.os }}-graalvm-native-

      # Build native executable using GraalVM native-image
      - name: Build Native Executable
        run: ./gradlew nativeCompile -x test --info
        env:
          JAVA_TOOL_OPTIONS: "${{ matrix.memory_options }} -Dnative-image.target-platform=${{ matrix.target_platform }} ${{ matrix.build_options }}"

      # Ensure the executable has execution permission
      - name: Make executable
        run: chmod +x build/native/nativeCompile/generator-cli

      # Set version variables
      - name: Set version
        run: |
          echo "VERSION=20240421.1" >> $GITHUB_ENV
          echo "RELEASE_TAG=v20240421.1" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release v20240421.1" >> $GITHUB_ENV
      
      # Prepare release files (keep only the zip archive)
      - name: Prepare release files
        run: |
          mkdir -p release
          echo "Copy and rename executable according to architecture"
          cp build/native/nativeCompile/generator-cli release/${{ matrix.artifact_name }}
          cd release
          echo "Create zip archive containing the executable"
          zip -r ${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }}
          echo "Remove original executable, keep only the zip"
          rm ${{ matrix.artifact_name }}
      
      # Upload build artifacts (only upload zip, short retention to save space)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release/${{ matrix.artifact_name }}.zip
          retention-days: 1

  # Job 2: Create GitHub Release
  # This job depends on build-and-release
  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (shallow checkout for speed)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      # Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      # Setup Gradle cache
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      
      # Generate CycloneDX SBOM
      - name: Generate CycloneDX SBOM
        run: |
          ./gradlew cyclonedxBom
          mkdir -p sbom
          cp build/reports/bom.json sbom/sbom.json

      # Generate SBOM HTML report using Sunshine
      - name: Generate SBOM HTML report using Sunshine
        run: |
          echo "Install Python (if needed)"
          python -m pip install --upgrade pip
          
          echo "Download Sunshine tool"
          curl -L -o sunshine.py https://raw.githubusercontent.com/CycloneDX/Sunshine/main/sunshine.py
          
          echo "Generate HTML report"
          python sunshine.py -i sbom/sbom.json -o sbom/sbom-report.html
      
      # Upload SBOM artifacts (short retention)
      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom/sbom.json
            sbom/sbom-report.html
          retention-days: 1

      # Download all build artifacts
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: release
      
      # Set version variables
      - name: Set version
        run: |
          echo "VERSION=20250421.1" >> $GITHUB_ENV
          echo "RELEASE_TAG=v20250421.1" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release v20250421.1" >> $GITHUB_ENV
          echo "INTEL_ARTIFACT=generator-cli-darwin-x86_64" >> $GITHUB_ENV
          echo "ARM_ARTIFACT=generator-cli-darwin-aarch64" >> $GITHUB_ENV
          echo "LINUX_ARTIFACT=generator-cli-linux-x86_64" >> $GITHUB_ENV
      
      # Prepare GitHub Pages content
      - name: Prepare GitHub Pages content
        run: |
          echo "Create GitHub Pages content directory"
          mkdir -p pages-content/sbom
          
          echo "Copy SBOM report"
          cp release/sbom-artifacts/sbom-report.html pages-content/sbom/index.html
          cp release/sbom-artifacts/sbom.json pages-content/sbom/sbom.json
      
      # Upload GitHub Pages content
      - name: Upload GitHub Pages content
        uses: actions/upload-artifact@v4
        with:
          name: pages-content
          path: pages-content
          retention-days: 1

      # Reorganize files for release (only process zip files)
      - name: Reorganize files
        run: |
          mkdir -p combined_release
          # Copy Intel artifacts
          cp release/${{ env.INTEL_ARTIFACT }}/${{ env.INTEL_ARTIFACT }}.zip combined_release/
          # Copy ARM artifacts
          cp release/${{ env.ARM_ARTIFACT }}/${{ env.ARM_ARTIFACT }}.zip combined_release/
          # Copy Linux artifacts
          cp release/${{ env.LINUX_ARTIFACT }}/${{ env.LINUX_ARTIFACT }}.zip combined_release/
          # Copy SBOM files (only one copy needed)
          cp release/sbom-artifacts/sbom.json combined_release/sbom.json
          cp release/sbom-artifacts/sbom-report.html combined_release/sbom-report.html

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            Spring Boot 專案產生工具
            
            這個開源專案提供了一個全面的程式碼產生工具，旨在簡化 Spring Boot 應用程序的建立過程。它無縫整合了 JOOQ、OpenAPI、JPA 以及 Liquibase，適合需要快速啟動並遵循最佳實踐的 Spring Boot 項目開發者。

            ## 特性
            - Spring Boot 整合：生成包含必要配置和依賴的 Spring Boot 項目
            - JOOQ Codegen：自動基於數據庫結構產生 JPA 實體
            - OpenAPI 規範：根據 OpenAPI 規範生成 API 文檔和服務器框架
            - Spring Data JPA：產生 Spring Data 資料訪問介面
            - Liquibase 遷移：使用 Liquibase 管理數據庫模式更改

            ## 下載
            目前提供以下版本：
            - Intel Mac (x86_64): ${{ env.INTEL_ARTIFACT }}.zip
            - ARM Mac (aarch64): ${{ env.ARM_ARTIFACT }}.zip
            - Linux (x86_64): ${{ env.LINUX_ARTIFACT }}.zip

            ## SBOM 資訊
            軟體物料清單 (SBOM) 檔案：
            - JSON 格式：sbom.json
            - HTML 報告：sbom-report.html

            查看完整的[互動式 SBOM 報告](https://samzhu.github.io/generator-cli/sbom/)

            ## 建置資訊
            建置時間：${{ github.event.repository.updated_at }}
            提交版本：${{ github.sha }}
          files: |
            combined_release/${{ env.INTEL_ARTIFACT }}.zip
            combined_release/${{ env.ARM_ARTIFACT }}.zip
            combined_release/${{ env.LINUX_ARTIFACT }}.zip
            combined_release/sbom.json
            combined_release/sbom-report.html

  # Job 3: Deploy GitHub Pages
  # This job depends on create-release
  deploy-pages:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      # Download GitHub Pages content (using latest v4)
      - name: Download GitHub Pages content
        uses: actions/download-artifact@v4
        with:
          name: pages-content
          path: site
      
      # Upload static site as artifact
      - name: Upload static site as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site  # Directory containing static site content
          # retention-days: 1  # Short retention to save space

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4